/* ============================================================
   CRUCIVERBA FINALE — WORDS + DEFINITIONS (300+)
   Format: { word: "PAROLA", def: "Definizione..." }
   ============================================================ */

const WORD_LIST = [
  // Animali
  { word: "ELEFANTE",    def: "Il mammifero terrestre più grande, con la proboscide" },
  { word: "PINGUINO",    def: "Uccello antartico che non vola ma nuota benissimo" },
  { word: "COCCODRILLO", def: "Rettile acquatico con mascella potentissima" },
  { word: "GIRAFFA",     def: "L'animale con il collo più lungo del mondo" },
  { word: "DELFINO",     def: "Mammifero marino intelligente e sorridente" },
  { word: "FARFALLA",    def: "Insetto dalle ali colorate, nasce da un bruco" },
  { word: "PIPISTRELLO", def: "L'unico mammifero capace di volare, esce di notte" },
  { word: "RINOCERONTE", def: "Mammifero africano con uno o due corni sul naso" },
  { word: "CAMALEON",    def: "Rettile che cambia colore per mimetizzarsi" },
  { word: "TARTARUGA",   def: "Rettile lentissimo con il guscio sulla schiena" },
  { word: "PAPPAGALLO",  def: "Uccello colorato capace di imitare la voce umana" },
  { word: "STRUZZO",     def: "Il più grande uccello del mondo, non vola" },
  { word: "CANGURO",     def: "Mammifero australiano che salta e porta i cuccioli nel marsupio" },
  { word: "GORILLA",     def: "Il più grande primate, vive in Africa" },
  { word: "LEOPARDO",    def: "Felino macchiettato, arrampicatore eccellente" },
  { word: "IPPOPOTAMO",  def: "Grosso mammifero semiaquatico africano" },
  { word: "FENICOTTERO", def: "Uccello rosa che sta su una zampa sola" },
  { word: "MEDUSA",      def: "Creatura marina gelatinosa che punge" },
  { word: "POLIPO",      def: "Mollusco marino con otto tentacoli" },
  { word: "LUCERTOLA",   def: "Piccolo rettile che lascia la coda per scappare" },

  // Luoghi e geografia
  { word: "HIMALAYA",    def: "La catena montuosa più alta del mondo, in Asia" },
  { word: "SAHARA",      def: "Il deserto caldo più grande del mondo, in Africa" },
  { word: "AMAZZONIA",   def: "La più grande foresta pluviale del mondo, in Brasile" },
  { word: "ANTARTIDE",   def: "Il continente più freddo e più meridionale del mondo" },
  { word: "VESUVIO",     def: "Il vulcano più famoso d'Italia, vicino a Napoli" },
  { word: "COLOSSEO",    def: "L'antico anfiteatro romano, simbolo di Roma" },
  { word: "PIRAMIDE",    def: "Monumentale tomba degli antichi faraoni egizi" },
  { word: "GONDOLA",     def: "L'imbarcazione tipica dei canali di Venezia" },
  { word: "PATAGONIA",   def: "Regione selvaggia all'estremità sud del Sudamerica" },
  { word: "MONGOLIA",    def: "Paese asiatico tra Russia e Cina, terra di Gengis Khan" },
  { word: "ISLANDA",     def: "Isola nordica famosa per i geyser e le aurore boreali" },
  { word: "SICILIA",     def: "La più grande isola del Mediterraneo" },
  { word: "TOSCANA",     def: "Regione italiana famosa per arte, vino e paesaggi collinari" },
  { word: "VENEZIA",     def: "Città italiana costruita sull'acqua" },
  { word: "ACROPOLI",    def: "L'antica rocca di Atene con il Partenone" },

  // Scienza e natura
  { word: "FOTOSINTESI", def: "Il processo con cui le piante producono nutrimento dalla luce" },
  { word: "VULCANO",     def: "Apertura nella crosta terrestre da cui fuoriesce lava" },
  { word: "TERREMOTO",   def: "Scuotimento improvviso del suolo causato da onde sismiche" },
  { word: "METEORITE",   def: "Roccia spaziale che cade sulla superficie terrestre" },
  { word: "ECLISSI",     def: "Oscuramento del sole o della luna per interposizione di un corpo celeste" },
  { word: "ATOMO",       def: "L'unità fondamentale della materia" },
  { word: "MOLECOLA",    def: "Unione di due o più atomi legati chimicamente" },
  { word: "GRAVITA",     def: "La forza che attrae i corpi tra loro, scoperta da Newton" },
  { word: "MAGNETISMO",  def: "Proprietà di attrazione tra poli opposti" },
  { word: "FOTONE",      def: "La particella elementare della luce" },
  { word: "OSMOSI",      def: "Passaggio di solvente attraverso membrana semipermeabile" },
  { word: "METAMORFOSI", def: "Trasformazione radicale di forma durante la crescita" },
  { word: "SIMBIOSI",    def: "Relazione di mutuo beneficio tra due specie diverse" },
  { word: "GALASSIA",    def: "Enorme sistema di stelle, gas e polvere cosmica" },
  { word: "SUPERNOVA",   def: "Esplosione stellare di straordinaria luminosità" },

  // Arte e cultura
  { word: "CAPOLAVORO",  def: "Opera di arte di altissimo livello e valore" },
  { word: "AFFRESCO",    def: "Tecnica pittorica su intonaco umido" },
  { word: "MOSAICO",     def: "Opera d'arte composta da piccole tessere colorate" },
  { word: "SCULTURA",    def: "Opera d'arte tridimensionale intagliata o modellata" },
  { word: "CATTEDRALE",  def: "Grande chiesa cristiana, sede del vescovo" },
  { word: "BASILICA",    def: "Importante chiesa cristiana di vasta dimensione" },
  { word: "LABIRINTO",   def: "Percorso intricato da cui è difficile uscire" },
  { word: "MITO",        def: "Racconto tradizionale di eroi, dei e origini del mondo" },
  { word: "EPOPEA",      def: "Lungo poema narrativo su imprese eroiche" },
  { word: "SONETTO",     def: "Componimento poetico di quattordici versi" },
  { word: "MELODIA",     def: "Successione di note musicali che forma un tema riconoscibile" },
  { word: "SINFONIA",    def: "Grande composizione orchestrale in più movimenti" },
  { word: "OPERA",       def: "Spettacolo teatrale cantato con musica orchestrale" },
  { word: "BALLETTO",    def: "Spettacolo di danza classica con musica" },
  { word: "COMMEDIA",    def: "Opera teatrale o cinematografica a lieto fine" },

  // Sport
  { word: "MARATONA",    def: "Gara di corsa su strada di 42,195 km" },
  { word: "DECATHLON",   def: "Competizione atletica composta da dieci discipline" },
  { word: "PENTATHLON",  def: "Competizione sportiva composta da cinque discipline" },
  { word: "TRIATHLON",   def: "Gara che combina nuoto, ciclismo e corsa" },
  { word: "TRAMPOLINO",  def: "Attrezzo elastico usato per i salti nella ginnastica" },
  { word: "PALLACANESTRO", def: "Sport di squadra in cui si tira in un canestro" },
  { word: "PALLAVOLO",   def: "Sport in cui si manda la palla oltre la rete" },
  { word: "SCHERMA",     def: "Sport da combattimento con spade, fioretto o sciabola" },
  { word: "EQUITAZIONE", def: "Sport che si pratica a cavallo" },
  { word: "CANOTTAGGIO", def: "Sport remiero su imbarcazioni strette e veloci" },
  { word: "SLALOM",      def: "Discesa sugli sci tra porte ravvicinate" },
  { word: "CICLISMO",    def: "Sport praticato su bicicletta in gara" },
  { word: "PUGILATO",    def: "Sport da combattimento con guantoni" },
  { word: "LOTTA",       def: "Sport da combattimento corpo a corpo" },
  { word: "ARRAMPICATA", def: "Sport che consiste nel scalare pareti rocciose" },

  // Cibo e gastronomia
  { word: "MOZZARELLA",  def: "Formaggio fresco tipico della Campania" },
  { word: "PROSCIUTTO",  def: "Salume italiano stagionato, tipico di Parma" },
  { word: "PARMIGIANO",  def: "Formaggio italiano duro e stagionato, re dei formaggi" },
  { word: "BRUSCHETTA",  def: "Fettina di pane tostato con pomodoro e basilico" },
  { word: "CANNOLI",     def: "Dolce siciliano a forma di tubo ripieno di ricotta" },
  { word: "TIRAMISÙ",    def: "Dolce italiano a strati di mascarpone e savoiardi" },
  { word: "RISOTTO",     def: "Piatto di riso cucinato lentamente con brodo" },
  { word: "GNOCCHI",     def: "Piccoli chicchi di pasta di patate" },
  { word: "FOCACCIA",    def: "Pane piatto morbido tipico della Liguria" },
  { word: "CARPACCIO",   def: "Piatto di carne o pesce crudo tagliato sottilissimo" },
  { word: "ESPRESSO",    def: "Caffè italiano corto e concentrato" },
  { word: "GELATO",      def: "Dolce ghiacciato tipico italiano" },
  { word: "PANETTONE",   def: "Dolce natalizio milanese a cupola con uvetta" },
  { word: "GRISSINI",    def: "Sottili bastoncini di pane croccante tipici di Torino" },
  { word: "MORTADELLA",  def: "Salume di maiale tipico di Bologna" },

  // Tecnologia e invenzioni
  { word: "TELESCOPIO",  def: "Strumento ottico per osservare corpi celesti lontani" },
  { word: "MICROSCOPIO", def: "Strumento per osservare oggetti invisibili a occhio nudo" },
  { word: "CALCOLATRICE", def: "Strumento elettronico per eseguire calcoli matematici" },
  { word: "BAROMETRO",   def: "Strumento per misurare la pressione atmosferica" },
  { word: "TERMOMETRO",  def: "Strumento per misurare la temperatura" },
  { word: "BUSSOLA",     def: "Strumento che indica il nord magnetico" },
  { word: "RADAR",       def: "Sistema di rilevamento a distanza tramite onde radio" },
  { word: "SATELLITE",   def: "Corpo artificiale in orbita intorno alla Terra" },
  { word: "SUBMARINE",   def: "Imbarcazione progettata per navigare sott'acqua" },
  { word: "ELICOTTERO",  def: "Aeromobile con rotore orizzontale che lo fa salire verticalmente" },
  { word: "LOCOMOTIVE",  def: "Macchina a vapore che trasmette il moto al treno" },
  { word: "TRANSISTOR",  def: "Componente elettronico che amplifica o commuta segnali" },
  { word: "OLOGRAMMA",   def: "Immagine tridimensionale creata con la luce laser" },
  { word: "LASER",       def: "Raggio di luce coerente e monocromatica ad alta intensità" },
  { word: "ALGORITMO",   def: "Sequenza di istruzioni per risolvere un problema" },

  // Persone e professioni storiche
  { word: "ASTRONAUTA",  def: "Chi viaggia nello spazio a bordo di navicelle" },
  { word: "ALCHIMISTA",  def: "Chi cercava di trasformare metalli in oro nel Medioevo" },
  { word: "AMBASCIATORE", def: "Diplomatico che rappresenta il proprio paese all'estero" },
  { word: "GIOCOLIERE",  def: "Artista di circo che lancia e riprende oggetti in aria" },
  { word: "GLADIATORE",  def: "Combattente nell'arena dell'antica Roma" },
  { word: "TROUBADOUR",  def: "Poeta e musicista itinerante del Medioevo" },
  { word: "CARTOGRAFO",  def: "Chi disegna mappe e carte geografiche" },
  { word: "CALLIGRAFO",  def: "Artista specializzato nella bella scrittura" },
  { word: "SOMMELIER",   def: "Esperto nella scelta e nel servizio dei vini" },
  { word: "CHIRURGO",    def: "Medico specializzato in operazioni e interventi" },

  // Oggetti e concetti astratti
  { word: "BUSSOLA",     def: "Strumento per orientarsi che punta sempre a nord" },
  { word: "LANTERNA",    def: "Lampada portatile con vetro protettivo" },
  { word: "ASTROLABIO",  def: "Antico strumento per misurare le posizioni degli astri" },
  { word: "PERGAMENA",   def: "Antica superficie di scrittura fatta con pelle animale" },
  { word: "CALEIDOSCOPIO", def: "Tubo con specchi e vetri colorati che crea figure simmetriche" },
  { word: "PARACADUTE",  def: "Dispositivo a cupola che rallenta la caduta dall'aereo" },
  { word: "XILOFONO",    def: "Strumento musicale a percussione con lamine di legno" },
  { word: "MANDOLINO",   def: "Strumento musicale a corde tipico della musica napoletana" },
  { word: "ARMONICA",    def: "Piccolo strumento a fiato che si suona con la bocca" },
  { word: "FISARMONICA", def: "Strumento musicale a mantice, tipico della musica popolare" },
  { word: "BOOMERANG",   def: "Oggetto curvo che, lanciato, torna al mittente" },
  { word: "ABACO",       def: "Antico strumento di calcolo con palline scorrevoli" },
  { word: "CLESSIDRA",   def: "Strumento per misurare il tempo con la sabbia" },
  { word: "PENDOLO",     def: "Peso appeso a un filo che oscilla con periodo costante" },
  { word: "PERISCOPO",   def: "Strumento ottico che permette di vedere oltre un ostacolo" },

  // Mitologia e fantasia
  { word: "FENICE",      def: "Uccello mitologico che rinasce dalle proprie ceneri" },
  { word: "MINOTAURO",   def: "Creatura metà uomo e metà toro nella mitologia greca" },
  { word: "CENTAURO",    def: "Creatura mitologica metà uomo e metà cavallo" },
  { word: "MEDUSA",      def: "Mostro mitologico con serpenti al posto dei capelli" },
  { word: "CHIMERA",     def: "Mostro mitologico con testa di leone, corpo di capra e coda di serpente" },
  { word: "CICLOPE",     def: "Gigante monocolo della mitologia greca" },
  { word: "UNICORNO",    def: "Creatura fantástica simile a un cavallo con un corno" },
  { word: "DRAGHETTO",   def: "Piccolo drago, creatura fantastica alata che sputa fuoco" },
  { word: "ARABA",       def: "Parola per indicare la fenice nelle versioni orientali" },
  { word: "SIRENA",      def: "Creatura mitologica metà donna e metà pesce" },

  // Parole difficili e interessanti
  { word: "ZAFFIRO",     def: "Pietra preziosa di colore blu intenso" },
  { word: "SMERALDO",    def: "Pietra preziosa di colore verde brillante" },
  { word: "RUBINO",      def: "Pietra preziosa di colore rosso fuoco" },
  { word: "AMBRA",       def: "Resina fossile trasparente di colore giallo-arancio" },
  { word: "QUARZO",      def: "Minerale cristallino molto comune nella crosta terrestre" },
  { word: "OPALE",       def: "Pietra preziosa con riflessi cangianti di vari colori" },
  { word: "TURCHESE",    def: "Pietra preziosa di colore blu-verde" },
  { word: "GRANATO",     def: "Pietra semipreziosa di colore rosso scuro" },
  { word: "AMETISTA",    def: "Varietà di quarzo di colore viola" },
  { word: "DIAMANTE",    def: "La pietra preziosa più dura che esiste" },
  { word: "LABIRINTO",   def: "Intrico di percorsi da cui è difficile uscire" },
  { word: "ENIGMA",      def: "Cosa oscura e difficile da capire o interpretare" },
  { word: "PARADOSSO",   def: "Affermazione che sembra contraddire il senso comune" },
  { word: "MERAVIGLIA",  def: "Sentimento di stupore e ammirazione per qualcosa di straordinario" },
  { word: "AVVENTURA",   def: "Esperienza emozionante e piena di rischi e scoperte" },
  { word: "ILLUSIONE",   def: "Percezione falsa della realtà" },
  { word: "NOSTALGIA",   def: "Dolce malinconia per un passato amato" },
  { word: "EUFORIA",     def: "Stato di gioia intensa e incontenibile" },
  { word: "SIMMETRIA",   def: "Corrispondenza esatta tra le parti di una figura" },
  { word: "CARISMA",     def: "Straordinario fascino personale che attira gli altri" },

  // Extra — parole italiane belle
  { word: "PENOMBRA",    def: "Zona di luce fioca tra la luce e l'ombra piena" },
  { word: "TORRENTE",    def: "Corso d'acqua impetuoso di montagna" },
  { word: "BREZZA",      def: "Vento leggero e piacevole" },
  { word: "BURRASCA",    def: "Tempesta di vento violenta" },
  { word: "CALURA",      def: "Caldo intenso e soffocante" },
  { word: "NEVISCHIO",   def: "Precipitazione di neve e pioggia mista" },
  { word: "TRAMONTO",    def: "Il momento in cui il sole scende sotto l'orizzonte" },
  { word: "AURORA",      def: "Il primo chiarore del giorno, prima del sorgere del sole" },
  { word: "CREPUSCOLO",  def: "Il periodo di luce diffusa dopo il tramonto" },
  { word: "CHIARORE",    def: "Luce tenue e diffusa" },
  { word: "SCINTILLA",   def: "Piccola particella luminosa che salta da un fuoco" },
  { word: "CRISTALLO",   def: "Solido con struttura molecolare ordinata e regolare" },
  { word: "RIFLESSO",    def: "Immagine restituita da una superficie lucida" },
  { word: "OMBRA",       def: "Zona buia proiettata da un corpo che intercetta la luce" },
  { word: "SILENZIO",    def: "Assenza totale di suono" },
  { word: "ARMONIA",     def: "Accordo piacevole tra elementi diversi" },
  { word: "ELEGANZA",    def: "Grazia e raffinatezza nello stile" },
  { word: "SPLENDORE",   def: "Grande bellezza e luminosità" },
  { word: "GRANDEZZA",   def: "Vastità imponente di dimensioni o importanza" },
  { word: "SAGGEZZA",    def: "Profonda comprensione della vita e delle cose" }
];
