/* ============================================================
   AVANTI UN ALTRO — QUESTIONS (500+)
   Format: { q: "Domanda?", a: "Risposta corretta" }
   Players must give a WRONG answer to score a point.
   ============================================================ */

const QUESTIONS = [
  // Colori
  { q: "Di che colore è il cielo sereno?", a: "Blu" },
  { q: "Di che colore è l'erba?", a: "Verde" },
  { q: "Di che colore è il sole?", a: "Giallo" },
  { q: "Di che colore è il sangue?", a: "Rosso" },
  { q: "Di che colore è la neve?", a: "Bianco" },
  { q: "Di che colore è il carbone?", a: "Nero" },
  { q: "Di che colore è il latte?", a: "Bianco" },
  { q: "Di che colore è un limone?", a: "Giallo" },
  { q: "Di che colore è un pomodoro maturo?", a: "Rosso" },
  { q: "Di che colore è una banana matura?", a: "Giallo" },
  { q: "Di che colore è un'arancia?", a: "Arancione" },
  { q: "Di che colore è il mare?", a: "Blu" },
  { q: "Di che colore è una ciliegia?", a: "Rosso" },
  { q: "Di che colore è il pepe nero?", a: "Nero" },
  { q: "Di che colore è la cioccolata?", a: "Marrone" },

  // Capitali
  { q: "Qual è la capitale dell'Italia?", a: "Roma" },
  { q: "Qual è la capitale della Francia?", a: "Parigi" },
  { q: "Qual è la capitale della Germania?", a: "Berlino" },
  { q: "Qual è la capitale della Spagna?", a: "Madrid" },
  { q: "Qual è la capitale del Portogallo?", a: "Lisbona" },
  { q: "Qual è la capitale dell'Inghilterra?", a: "Londra" },
  { q: "Qual è la capitale degli USA?", a: "Washington" },
  { q: "Qual è la capitale del Giappone?", a: "Tokyo" },
  { q: "Qual è la capitale della Cina?", a: "Pechino" },
  { q: "Qual è la capitale dell'Australia?", a: "Canberra" },
  { q: "Qual è la capitale del Brasile?", a: "Brasilia" },
  { q: "Qual è la capitale dell'Argentina?", a: "Buenos Aires" },
  { q: "Qual è la capitale della Russia?", a: "Mosca" },
  { q: "Qual è la capitale del Canada?", a: "Ottawa" },
  { q: "Qual è la capitale della Grecia?", a: "Atene" },
  { q: "Qual è la capitale dell'Olanda?", a: "Amsterdam" },
  { q: "Qual è la capitale del Belgio?", a: "Bruxelles" },
  { q: "Qual è la capitale della Svezia?", a: "Stoccolma" },
  { q: "Qual è la capitale della Norvegia?", a: "Oslo" },
  { q: "Qual è la capitale della Danimarca?", a: "Copenaghen" },
  { q: "Qual è la capitale della Polonia?", a: "Varsavia" },
  { q: "Qual è la capitale dell'Ungheria?", a: "Budapest" },
  { q: "Qual è la capitale della Repubblica Ceca?", a: "Praga" },
  { q: "Qual è la capitale dell'Austria?", a: "Vienna" },
  { q: "Qual è la capitale della Svizzera?", a: "Berna" },
  { q: "Qual è la capitale dell'Egitto?", a: "Il Cairo" },
  { q: "Qual è la capitale del Messico?", a: "Città del Messico" },
  { q: "Qual è la capitale dell'India?", a: "Nuova Delhi" },
  { q: "Qual è la capitale della Turchia?", a: "Ankara" },
  { q: "Qual è la capitale della Corea del Sud?", a: "Seoul" },

  // Numeri e matematica
  { q: "Quanti giorni ha una settimana?", a: "7" },
  { q: "Quanti mesi ha un anno?", a: "12" },
  { q: "Quante ore ha un giorno?", a: "24" },
  { q: "Quanti minuti ha un'ora?", a: "60" },
  { q: "Quanti secondi ha un minuto?", a: "60" },
  { q: "Quanti giorni ha febbraio (anno normale)?", a: "28" },
  { q: "Quante settimane ha un anno?", a: "52" },
  { q: "Quanto fa 2 + 2?", a: "4" },
  { q: "Quanto fa 3 x 3?", a: "9" },
  { q: "Quanto fa 10 x 10?", a: "100" },
  { q: "Quanto fa 5 x 5?", a: "25" },
  { q: "Quanto fa 100 diviso 10?", a: "10" },
  { q: "Quanto fa 7 x 8?", a: "56" },
  { q: "Quante sono le zampe di un cane?", a: "4" },
  { q: "Quante sono le dita di una mano?", a: "5" },
  { q: "Quante sono le dita di due mani?", a: "10" },
  { q: "Quanti lati ha un triangolo?", a: "3" },
  { q: "Quanti lati ha un quadrato?", a: "4" },
  { q: "Quanti lati ha un pentagono?", a: "5" },
  { q: "Quanti lati ha un esagono?", a: "6" },
  { q: "Quanti angoli ha un rettangolo?", a: "4" },
  { q: "Quanto fa la radice quadrata di 9?", a: "3" },
  { q: "Quanto fa la radice quadrata di 16?", a: "4" },
  { q: "Quante facce ha un cubo?", a: "6" },
  { q: "Quanto fa 1000 + 1?", a: "1001" },

  // Animali
  { q: "Quante gambe ha un ragno?", a: "8" },
  { q: "Quante gambe ha un insetto?", a: "6" },
  { q: "Di che animale è il verso 'miao'?", a: "Gatto" },
  { q: "Di che animale è il verso 'bau'?", a: "Cane" },
  { q: "Di che animale è il verso 'muuu'?", a: "Mucca" },
  { q: "Quale animale fa le uova e non è un uccello?", a: "Coccodrillo / Rettile" },
  { q: "Qual è il mammifero più grande del mondo?", a: "Balenottera azzurra" },
  { q: "Qual è l'animale più veloce sulla terra?", a: "Ghepardo" },
  { q: "Dove vive il pinguino?", a: "Antartide" },
  { q: "Di cosa si nutre il koala?", a: "Foglie di eucalipto" },
  { q: "Quante zampe ha un gatto?", a: "4" },
  { q: "Come si chiama il cucciolo del cavallo?", a: "Puledro" },
  { q: "Come si chiama il cucciolo del cane?", a: "Cucciolo / Cagnolino" },
  { q: "Quale animale ha la proboscide?", a: "Elefante" },
  { q: "Quale animale porta il guscio sulla schiena?", a: "Tartaruga / Lumaca" },
  { q: "Di che colore è uno scoiattolo tipico?", a: "Rosso/Marrone" },
  { q: "Quante gobba ha il dromedario?", a: "1" },
  { q: "Quante gobba ha il cammello?", a: "2" },
  { q: "Dove vive il canguro?", a: "Australia" },
  { q: "Quale animale simboleggia la pace?", a: "Colomba" },

  // Geografia
  { q: "Qual è il fiume più lungo del mondo?", a: "Nilo / Amazzoni" },
  { q: "Qual è la montagna più alta del mondo?", a: "Everest" },
  { q: "Qual è l'oceano più grande del mondo?", a: "Pacifico" },
  { q: "Qual è il continente più grande?", a: "Asia" },
  { q: "Qual è il continente più piccolo?", a: "Oceania / Australia" },
  { q: "In quale continente si trova l'Italia?", a: "Europa" },
  { q: "In quale continente si trova il Brasile?", a: "Sud America" },
  { q: "Quanti continenti ci sono?", a: "7" },
  { q: "Qual è il deserto più grande del mondo?", a: "Sahara" },
  { q: "Qual è il paese più grande del mondo?", a: "Russia" },
  { q: "Quale fiume attraversa Parigi?", a: "Senna" },
  { q: "Quale fiume attraversa Roma?", a: "Tevere" },
  { q: "Quale fiume attraversa Londra?", a: "Tamigi" },
  { q: "Quale fiume attraversa Firenze?", a: "Arno" },
  { q: "Quale lago si trova tra Italia e Svizzera?", a: "Lago Maggiore / Lago di Lugano" },
  { q: "Qual è l'isola più grande del Mediterraneo?", a: "Sicilia" },
  { q: "Qual è il polo geografico a nord?", a: "Polo Nord" },
  { q: "In quale stato si trova Hollywood?", a: "California" },
  { q: "Quanti stati ha gli USA?", a: "50" },
  { q: "Qual è il paese più popoloso del mondo?", a: "India / Cina" },

  // Scienza e natura
  { q: "Quanti pianeti ci sono nel sistema solare?", a: "8" },
  { q: "Qual è il pianeta più vicino al sole?", a: "Mercurio" },
  { q: "Qual è il pianeta più grande del sistema solare?", a: "Giove" },
  { q: "Quante lune ha la Terra?", a: "1" },
  { q: "A quanti gradi bolle l'acqua?", a: "100" },
  { q: "A quanti gradi ghiaccia l'acqua?", a: "0" },
  { q: "Qual è il simbolo chimico dell'oro?", a: "Au" },
  { q: "Qual è il simbolo chimico dell'acqua?", a: "H2O" },
  { q: "Qual è il gas più abbondante nell'atmosfera?", a: "Azoto" },
  { q: "Di cosa hanno bisogno le piante per la fotosintesi?", a: "Luce solare e CO2" },
  { q: "Quante ossa ha il corpo umano adulto?", a: "206" },
  { q: "Qual è l'organo più grande del corpo umano?", a: "Pelle" },
  { q: "Quante camere ha il cuore umano?", a: "4" },
  { q: "Quale vitamina produce la pelle con il sole?", a: "Vitamina D" },
  { q: "Qual è la velocità della luce?", a: "300.000 km/s" },
  { q: "Qual è la formula della gravità di Newton?", a: "F = G*m1*m2/r²" },
  { q: "Da cosa è composta l'acqua?", a: "Idrogeno e Ossigeno" },
  { q: "Qual è il pianeta più lontano dal sole nel sistema solare?", a: "Nettuno" },
  { q: "Cos'è la stella più vicina alla Terra?", a: "Sole" },
  { q: "In quale stato si trova il ferro a temperatura ambiente?", a: "Solido" },

  // Storia e cultura
  { q: "Chi ha dipinto la Gioconda?", a: "Leonardo da Vinci" },
  { q: "Chi ha scritto la Divina Commedia?", a: "Dante Alighieri" },
  { q: "In che anno è caduto il muro di Berlino?", a: "1989" },
  { q: "In che anno è sbarcato l'uomo sulla Luna?", a: "1969" },
  { q: "Chi era il primo astronauta a camminare sulla Luna?", a: "Neil Armstrong" },
  { q: "Quante stelle ha la bandiera degli USA?", a: "50" },
  { q: "Quante strisce ha la bandiera degli USA?", a: "13" },
  { q: "Chi ha inventato la lampadina?", a: "Thomas Edison" },
  { q: "Chi ha inventato il telefono?", a: "Alexander Graham Bell" },
  { q: "Chi ha scoperto l'America?", a: "Cristoforo Colombo" },
  { q: "In che anno è avvenuta la scoperta dell'America?", a: "1492" },
  { q: "Chi ha scritto Romeo e Giulietta?", a: "William Shakespeare" },
  { q: "Chi ha composto la Quinta Sinfonia?", a: "Beethoven" },
  { q: "Chi era il faraone più famoso dell'antico Egitto?", a: "Tutankhamon / Ramesse II" },
  { q: "Quanti anni durò la guerra di Troia secondo il mito?", a: "10" },
  { q: "Chi era il re degli dei nella mitologia greca?", a: "Zeus" },
  { q: "Chi era il dio del mare nella mitologia greca?", a: "Poseidone" },
  { q: "Chi era il dio del sole nella mitologia romana?", a: "Apollo" },
  { q: "Chi ha dipinto il Giudizio Universale nella Cappella Sistina?", a: "Michelangelo" },
  { q: "Quante lettere ha l'alfabeto italiano?", a: "21" },
  { q: "Quante lettere ha l'alfabeto inglese?", a: "26" },

  // Sport
  { q: "Quanti giocatori ha una squadra di calcio in campo?", a: "11" },
  { q: "Quanti giocatori ha una squadra di pallacanestro in campo?", a: "5" },
  { q: "Quanti giocatori ha una squadra di pallavolo in campo?", a: "6" },
  { q: "Quanti set si giocano nel tennis (uomini, Slam)?", a: "5" },
  { q: "Quanti pali ha una porta del calcio?", a: "2 + traversa" },
  { q: "In quale sport si usa il termine 'ace'?", a: "Tennis" },
  { q: "In quale sport si usa il termine 'strike'?", a: "Bowling / Baseball" },
  { q: "In quale sport si usa il termine 'slam dunk'?", a: "Basket" },
  { q: "Ogni quanti anni si disputano le Olimpiadi?", a: "4" },
  { q: "In quale paese sono nate le Olimpiadi?", a: "Grecia" },
  { q: "Quanti cerchi ha il simbolo olimpico?", a: "5" },
  { q: "Qual è il trofeo del campionato di calcio italiano?", a: "Coppa/Scudetto" },
  { q: "Quale paese ha vinto più Mondiali di calcio?", a: "Brasile" },
  { q: "Quante volte l'Italia ha vinto i Mondiali di calcio?", a: "4" },
  { q: "Su quale superficie si gioca Wimbledon?", a: "Erba" },
  { q: "Quale sport si gioca al Roland Garros?", a: "Tennis" },
  { q: "Su quale superficie si gioca il Roland Garros?", a: "Terra battuta" },
  { q: "Quante buche ha un campo da golf standard?", a: "18" },
  { q: "Quanto dura un tempo nel calcio?", a: "45 minuti" },
  { q: "Qual è la lunghezza standard di una maratona?", a: "42,195 km" },

  // Cibo e cucina
  { q: "Da quale frutto si fa il vino?", a: "Uva" },
  { q: "Da quale frutto si fa la birra?", a: "Orzo (cereale)" },
  { q: "Quale formaggio italiano ha i buchi?", a: "Emmental / Grana" },
  { q: "Da dove viene la pizza?", a: "Napoli / Italia" },
  { q: "Qual è l'ingrediente principale del guacamole?", a: "Avocado" },
  { q: "Da quale animale viene il latte che usiamo di più?", a: "Mucca" },
  { q: "Quante uova ha tipicamente un uovo?", a: "1" },
  { q: "Da cosa si fa la farina?", a: "Grano" },
  { q: "Qual è il principale ingrediente del pane?", a: "Farina" },
  { q: "Da quale paese viene il sushi?", a: "Giappone" },
  { q: "Qual è la salsa più famosa della cucina italiana?", a: "Pomodoro" },
  { q: "Da quale pianta si ricava il cacao?", a: "Cacao / Theobroma cacao" },
  { q: "Qual è il caffè più corto e concentrato?", a: "Espresso" },
  { q: "Da quale animale si ottiene il miele?", a: "Ape" },
  { q: "Quale spezia è la più costosa al mondo?", a: "Zafferano" },
  { q: "Dove è nata la pasta?", a: "Italia / Cina" },
  { q: "Cosa si usa per fare il pesto genovese?", a: "Basilico" },
  { q: "Quale verdura rende le urine di odore strano?", a: "Asparagi" },
  { q: "Qual è il frutto del pino?", a: "Pigna / Pinolo" },
  { q: "Quale formaggio francese è famoso per la muffa?", a: "Roquefort / Brie" },

  // Tecnologia e cultura pop
  { q: "Chi ha fondato Apple?", a: "Steve Jobs" },
  { q: "Chi ha fondato Microsoft?", a: "Bill Gates" },
  { q: "Chi ha fondato Amazon?", a: "Jeff Bezos" },
  { q: "Quale azienda produce l'iPhone?", a: "Apple" },
  { q: "Quale azienda produce l'Android?", a: "Google" },
  { q: "In quale anno è stato fondato Facebook?", a: "2004" },
  { q: "Chi è il protagonista di Harry Potter?", a: "Harry Potter" },
  { q: "Chi è il protagonista de Il Signore degli Anelli?", a: "Frodo Baggins" },
  { q: "Chi è il villain principale di Star Wars?", a: "Darth Vader" },
  { q: "Come si chiama il pianeta di Superman?", a: "Krypton" },
  { q: "Quale supereroe è anche Bruce Wayne?", a: "Batman" },
  { q: "Quale supereroe è anche Peter Parker?", a: "Spider-Man" },
  { q: "Quale supereroe è anche Tony Stark?", a: "Iron Man" },
  { q: "Quale supereroe è anche Bruce Banner?", a: "Hulk" },
  { q: "Chi è la principessa più famosa di Disney?", a: "Cenerentola / Biancaneve" },
  { q: "In quale città vive Batman?", a: "Gotham City" },
  { q: "In quale città vive Spider-Man?", a: "New York" },
  { q: "Chi canta 'Thriller'?", a: "Michael Jackson" },
  { q: "Chi canta 'Like a Prayer'?", a: "Madonna" },
  { q: "Da quanti film è composta la trilogia originale di Star Wars?", a: "3" },

  // Linguaggio e letteratura
  { q: "Quante vocali ha l'alfabeto italiano?", a: "5" },
  { q: "Qual è il contrario di 'grande'?", a: "Piccolo" },
  { q: "Qual è il contrario di 'caldo'?", a: "Freddo" },
  { q: "Qual è il contrario di 'luce'?", a: "Buio / Oscurità" },
  { q: "Qual è il contrario di 'veloce'?", a: "Lento" },
  { q: "Qual è il plurale di 'uomo'?", a: "Uomini" },
  { q: "Come si dice 'grazie' in inglese?", a: "Thank you" },
  { q: "Come si dice 'cane' in inglese?", a: "Dog" },
  { q: "Come si dice 'casa' in inglese?", a: "House" },
  { q: "Come si dice 'acqua' in spagnolo?", a: "Agua" },
  { q: "Come si dice 'buongiorno' in francese?", a: "Bonjour" },
  { q: "Come si dice 'grazie' in tedesco?", a: "Danke" },
  { q: "Chi ha scritto 'I Promessi Sposi'?", a: "Alessandro Manzoni" },
  { q: "Chi ha scritto 'L'Odissea'?", a: "Omero" },
  { q: "Chi ha scritto 'L'Iliade'?", a: "Omero" },
  { q: "Chi ha scritto 'Don Chisciotte'?", a: "Cervantes" },
  { q: "Chi ha scritto '1984'?", a: "George Orwell" },
  { q: "Chi ha scritto 'Il Piccolo Principe'?", a: "Antoine de Saint-Exupéry" },
  { q: "In quale libro appare il personaggio di Sherlock Holmes?", a: "Storie di A.C. Doyle" },
  { q: "Chi ha scritto 'Delitto e Castigo'?", a: "Dostoevskij" },

  // Musica
  { q: "Quante corde ha una chitarra classica?", a: "6" },
  { q: "Quante corde ha un violino?", a: "4" },
  { q: "Quanti tasti bianchi ha una tastiera pianistica standard?", a: "52" },
  { q: "Di quante note è composta la scala musicale?", a: "7" },
  { q: "Come si chiama il simbolo musicale che indica il silenzio?", a: "Pausa" },
  { q: "Quale strumento è considerato il re degli strumenti?", a: "Organo / Pianoforte" },
  { q: "Quanti membri avevano i Beatles?", a: "4" },
  { q: "Da quale paese vengono i Beatles?", a: "Inghilterra" },
  { q: "Come si chiama la nota più acuta in Do maggiore?", a: "Do (ottava superiore)" },
  { q: "Chi ha composto la 'Nona Sinfonia'?", a: "Beethoven" },
  { q: "Chi ha composto 'Le Quattro Stagioni'?", a: "Vivaldi" },
  { q: "Chi ha composto 'La Traviata'?", a: "Verdi" },
  { q: "Quale strumento suona il jazzista Miles Davis?", a: "Tromba" },
  { q: "Quale nota segue il 'La' nella scala?", a: "Si" },
  { q: "Quale nota precede il 'Re' nella scala?", a: "Do" },

  // Cinema e TV
  { q: "In quale film appare il personaggio di 'Forrest Gump'?", a: "Forrest Gump" },
  { q: "Chi interpreta Jack in 'Titanic'?", a: "Leonardo DiCaprio" },
  { q: "Quale attore interpreta Iron Man?", a: "Robert Downey Jr." },
  { q: "Quale attore interpreta Captain America?", a: "Chris Evans" },
  { q: "In quale film c'è la frase 'Io sono tuo padre'?", a: "Star Wars" },
  { q: "Qual è il film d'animazione con il pesce Nemo?", a: "Alla ricerca di Nemo" },
  { q: "Quale studio ha creato i film di Toy Story?", a: "Pixar" },
  { q: "In quale film c'è un leone di nome Simba?", a: "Il Re Leone" },
  { q: "Quale attore ha interpretato James Bond più spesso?", a: "Roger Moore" },
  { q: "Chi ha diretto il film 'Schindler's List'?", a: "Steven Spielberg" },
  { q: "Chi ha diretto 'Il padrino'?", a: "Francis Ford Coppola" },
  { q: "Quale serie TV si svolge a Westeros?", a: "Il Trono di Spade" },
  { q: "In quale stato americano si svolge 'Breaking Bad'?", a: "New Mexico" },
  { q: "Qual è il personaggio principale di 'The Office'?", a: "Michael Scott" },
  { q: "Chi sono i protagonisti di 'Friends'?", a: "Ross, Rachel, Monica, Chandler, Joey, Phoebe" },

  // Varie e curiosità
  { q: "Quanti secondi ci sono in un'ora?", a: "3600" },
  { q: "Qual è il numero più piccolo positivo intero?", a: "1" },
  { q: "Quante carte ci sono in un mazzo standard?", a: "52" },
  { q: "Quanti semi ha un mazzo di carte?", a: "4" },
  { q: "Quante facce ha un dado standard?", a: "6" },
  { q: "Quale pezzo degli scacchi si muove solo in diagonale?", a: "Alfiere" },
  { q: "Quale pezzo degli scacchi può saltare gli altri?", a: "Cavallo" },
  { q: "Quanti pezzi ha ogni giocatore agli scacchi?", a: "16" },
  { q: "Quale pianeta è chiamato il 'pianeta rosso'?", a: "Marte" },
  { q: "Quale pianeta ha gli anelli più famosi?", a: "Saturno" },
  { q: "Qual è la moneta dell'Italia?", a: "Euro" },
  { q: "Qual è la moneta degli USA?", a: "Dollaro" },
  { q: "Qual è la moneta del Giappone?", a: "Yen" },
  { q: "Qual è la moneta dell'Inghilterra?", a: "Sterlina" },
  { q: "Quante regioni ha l'Italia?", a: "20" },
  { q: "Quante province ha la Lombardia?", a: "12" },
  { q: "Qual è il capoluogo della Toscana?", a: "Firenze" },
  { q: "Qual è il capoluogo della Sicilia?", a: "Palermo" },
  { q: "Qual è il capoluogo della Sardegna?", a: "Cagliari" },
  { q: "Qual è il capoluogo del Veneto?", a: "Venezia" },
  { q: "Qual è il capoluogo del Piemonte?", a: "Torino" },
  { q: "Qual è la regione più grande d'Italia?", a: "Sicilia" },
  { q: "Qual è la regione più piccola d'Italia?", a: "Valle d'Aosta" },
  { q: "In quale regione si trova Napoli?", a: "Campania" },
  { q: "In quale regione si trova Bologna?", a: "Emilia-Romagna" },
  { q: "Da quanti stati è composta l'Unione Europea?", a: "27" },
  { q: "In che anno è stata fondata l'Unione Europea?", a: "1993 (Maastricht)" },
  { q: "In che anno l'Italia è diventata una Repubblica?", a: "1946" },
  { q: "Chi è stato il primo presidente della Repubblica Italiana?", a: "Enrico De Nicola" },
  { q: "Quanti articoli ha la Costituzione Italiana?", a: "139" },
  { q: "Quale santo è il patrono d'Italia?", a: "San Francesco d'Assisi" },
  { q: "Quale santo è il patrono di Roma?", a: "San Pietro e San Paolo" },
  { q: "Quale animale simboleggia la forza nel leone?", a: "Leone" },
  { q: "Quale elemento chimico ha numero atomico 1?", a: "Idrogeno" },
  { q: "Quale elemento chimico è rappresentato da Fe?", a: "Ferro" },
  { q: "Quale elemento chimico è rappresentato da Na?", a: "Sodio" },
  { q: "Quale elemento chimico è rappresentato da K?", a: "Potassio" },
  { q: "Quale elemento chimico è rappresentato da Ag?", a: "Argento" },
  { q: "Quale elemento chimico è rappresentato da Pb?", a: "Piombo" },
  { q: "Quale elemento chimico è rappresentato da Cu?", a: "Rame" },
  { q: "Quanti grammi ci sono in un chilogrammo?", a: "1000" },
  { q: "Quanti centimetri ci sono in un metro?", a: "100" },
  { q: "Quanti millimetri ci sono in un centimetro?", a: "10" },
  { q: "Quanti metri ci sono in un chilometro?", a: "1000" },
  { q: "Quanti litri ci sono in un ettolitro?", a: "100" },
  { q: "A quanti gradi si misura la temperatura corporea normale?", a: "36-37°C" },
  { q: "Quanti anni dura un mandato presidenziale negli USA?", a: "4" },
  { q: "Chi scrive le leggi in Italia?", a: "Parlamento" },
  { q: "Quante camere ha il Parlamento italiano?", a: "2" },
  { q: "Come si chiama la camera alta del Parlamento italiano?", a: "Senato" },
  { q: "Come si chiama la camera bassa del Parlamento italiano?", a: "Camera dei Deputati" },
  { q: "Chi è il capo dello Stato in Italia?", a: "Presidente della Repubblica" },
  { q: "Quanti anni dura il mandato del Presidente della Repubblica Italiana?", a: "7" },
  { q: "Quale organismo internazionale ha sede a New York?", a: "ONU" },
  { q: "In quante lingue parla il Papa?", a: "Molte / Dipende dal Papa" },
  { q: "Dove si trova il Vaticano?", a: "Roma" },
  { q: "Qual è la religione più diffusa al mondo?", a: "Cristianesimo" }
];
